"""add approval

Revision ID: 168d4371d276
Revises: 574549132936
Create Date: 2024-07-26 16:54:35.640877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '168d4371d276'
down_revision = '574549132936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval', sa.String(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients_history', schema=None) as batch_op:
        batch_op.drop_column('approval')

    # ### end Alembic commands ###
