"""add date on rating

Revision ID: 574549132936
Revises: 8289e2af390f
Create Date: 2024-07-23 14:30:36.503622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '574549132936'
down_revision = '8289e2af390f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating_and_remarks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating_and_remarks', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
