"""change columns

Revision ID: 6d3ae05a4598
Revises: 017cf2646dfb
Create Date: 2024-07-16 16:28:53.923805

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6d3ae05a4598'
down_revision = '017cf2646dfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('physician_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('meeting_url', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('meeting_location', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('patient_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.drop_constraint('sessions_physicianId_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['physician_id'], ['id'])
        batch_op.drop_column('patientDetails')
        batch_op.drop_column('meetingUrl')
        batch_op.drop_column('physicianId')
        batch_op.drop_column('meetingLocation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meetingLocation', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('physicianId', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('meetingUrl', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('patientDetails', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('sessions_physicianId_fkey', 'users', ['physicianId'], ['id'])
        batch_op.drop_column('patient_details')
        batch_op.drop_column('meeting_location')
        batch_op.drop_column('meeting_url')
        batch_op.drop_column('physician_id')

    # ### end Alembic commands ###
