"""change requirements

Revision ID: 763f495f43a5
Revises: 9da70ee909d0
Create Date: 2024-07-16 17:22:52.966877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '763f495f43a5'
down_revision = '9da70ee909d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('meeting_url',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('meeting_location',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('meeting_location',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('meeting_url',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###
