"""approval

Revision ID: 8cb81d4d9cac
Revises: 168d4371d276
Create Date: 2024-07-26 18:27:51.800187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cb81d4d9cac'
down_revision = '168d4371d276'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients_history') as batch_op:
        batch_op.alter_column(
            'approval',
            existing_type=sa.String(),
            type_=sa.Boolean(),
            postgresql_using="approval::boolean"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients_history') as batch_op:
        batch_op.alter_column(
            'approval',
            existing_type=sa.Boolean(),
            type_=sa.String()
        )

    # ### end Alembic commands ###
