"""include tasks

Revision ID: 8cc6f408240e
Revises: 9a357b8c3efd
Create Date: 2024-07-16 12:39:42.795882

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8cc6f408240e'
down_revision = '9a357b8c3efd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctorId', sa.Integer(), nullable=False),
    sa.Column('patientID', sa.Integer(), nullable=False),
    sa.Column('patientName', sa.String(length=200), nullable=False),
    sa.Column('activities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('remaining_time', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctorId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patientID'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
