"""feat: create sessions table

Revision ID: 9c56aeb57b8c
Revises: 3f703d8d8095
Create Date: 2024-07-16 16:19:23.876910

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9c56aeb57b8c'
down_revision = '3f703d8d8095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('physicianId', sa.Integer(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.Column('meetingUrl', sa.String(length=200), nullable=False),
    sa.Column('meetingLocation', sa.String(length=200), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('session_time', sa.DateTime(), nullable=False),
    sa.Column('patientDetails', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['physicianId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    # ### end Alembic commands ###
