"""add sessions

Revision ID: 9f8ff7b31022
Revises: faa17e9e34d5
Create Date: 2024-07-27 19:21:46.625383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f8ff7b31022'
down_revision = 'faa17e9e34d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions_', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions_', schema=None) as batch_op:
        batch_op.drop_column('approved')

    # ### end Alembic commands ###
