"""change column names

Revision ID: ee7d190b1c01
Revises: 8cc6f408240e
Create Date: 2024-07-16 12:55:49.138193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee7d190b1c01'
down_revision = '8cc6f408240e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('patient_name', sa.String(length=200), nullable=False))
        batch_op.drop_constraint('tasks_doctorId_fkey', type_='foreignkey')
        batch_op.drop_constraint('tasks_patientID_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['doctor_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['patient_id'], ['id'])
        batch_op.drop_column('patientID')
        batch_op.drop_column('doctorId')
        batch_op.drop_column('patientName')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patientName', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('doctorId', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('patientID', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tasks_patientID_fkey', 'users', ['patientID'], ['id'])
        batch_op.create_foreign_key('tasks_doctorId_fkey', 'users', ['doctorId'], ['id'])
        batch_op.drop_column('patient_name')
        batch_op.drop_column('patient_id')
        batch_op.drop_column('doctor_id')

    # ### end Alembic commands ###
